export const AUTOPULL_ALERT_CODES = {
  NO_SOURCE_CONFIG: 'NO_SOURCE_CONFIG',
  NO_ACTIVE_TOPIC: 'NO_ACTIVE_TOPIC',
  SOURCE_UNREACHABLE: 'SOURCE_UNREACHABLE',
  SOURCE_AUTH_ERROR: 'SOURCE_AUTH_ERROR',
  SOURCE_RATE_LIMIT: 'SOURCE_RATE_LIMIT',
  PARSE_FAILED: 'PARSE_FAILED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  QUALITY_SCORE_UNAVAILABLE: 'QUALITY_SCORE_UNAVAILABLE',
  RUN_SKIPPED_SINGLE_FLIGHT: 'RUN_SKIPPED_SINGLE_FLIGHT',
} as const;
