// T-127 W-09 (DP-3.5) step S4 — CONCRETE named provider-diverse debate execution-plan registries.
//
// This is the ONLY slice that AUTHORS + SELECTS a plan; S1/S2/S3 only threaded the (absent-by-default)
// plan through N8 / N6 / v1c-N2. Each family gets three named plans (codex_assisted / provider_compact /
// provider_diverse) whose per-role model_option_ids are REAL, profile-key-scoped option ids derived from
// the SAME profile-id constants the model-profile registry uses (so a literal can never drift). The shape
// + resolver + level mapping live in the shared leaf (topic-selection-debate-execution-plan-contracts);
// the concrete provider literals live here, backend-side, next to the model-profile registry.
//
// ──────────────────────────────────────────────────────────────────────────────────────────────────────
// LOUD BOUNDARY — identity/provenance, NOT live provider execution (the single most misread thing here):
//   N8 and N6 debates run codex_assisted | mocked_llm ONLY (their runtime input restricts execution_mode to
//   Extract<…, 'codex_assisted' | 'mocked_llm'>). There is NO live provider_llm debate path in W-09.
//   Therefore a per-role model_option_id selected by one of these plans changes the PROMPT-PACKET IDENTITY
//   and PROVENANCE metadata of the debate — it does NOT change the provider that actually executes. No
//   openai/dashscope call is made for these debates in W-09. A "provider_diverse" run is selectable and
//   identity-bearing, NOT live multi-provider execution. True per-role multi-provider EXECUTION is OUT of
//   W-09 scope.
//
// SCOPE NOTES:
//   - deepseek is structurally UNAVAILABLE on the debate profiles (the registry's deepseek gate covers only
//     the need-discovery explorer/deep-critic profiles). So provider_diverse here = openai-vs-dashscope
//     only; widening the deepseek eligibility set is a registry change deliberately OUT of scope (it would
//     perturb the N6 per-role profile hashes). The "deepseek explorer/critic-eligible, never arbiter" rule
//     is still encoded as a guard test: no plan ever assigns deepseek, and the arbiter/final terminal role
//     always takes the highest-quality openai option, never an alternative-worker provider.
//   - provider_fallback_policy is NOT added: the model-profile registry pins an anti-fallback stance
//     (automatic_fallback:false, provider_failure_result:'blocked', validator-enforced), so an unavailable
//     provider stays "blocked" rather than silently falling back. A per-role fallback list would contradict
//     that v1 stance; deferred until (and if) live provider debate execution lands post-W-09.

import type {
  TopicSelectionAgentExecutionSpec,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-agent-profile-contracts';
import {
  type TopicSelectionDebateExecutionPlanName,
  type TopicSelectionNamedDebateExecutionPlan,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-debate-execution-plan-contracts';
import {
  TOPIC_SELECTION_V1B_N6_DEBATE_ARBITER_PROFILE_ID,
  TOPIC_SELECTION_V1B_N6_DEBATE_CRITIC_PROFILE_ID,
  TOPIC_SELECTION_V1B_N6_DEBATE_EXPLORER_PROFILE_ID,
  type TopicSelectionV1bN6DivergentDebateRoleSlotId,
  type TopicSelectionV1bN8BoundedDebateRoleSlotId,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-v1b-workflow-harness-contracts';
import {
  TOPIC_SELECTION_V1B_N8_BOUNDED_DEBATE_PROFILE_ID,
  TOPIC_SELECTION_V1C_BOUNDED_MICRO_DEBATE_PROFILE_ID,
} from './topic-selection-model-profile-registry-service.js';
import type {
  TopicSelectionV1cN2BoundedDebateRoleSlotId,
} from './topic-selection-v1c-n2-bounded-debate-admission-service.js';

/** The provider-option suffixes generated by the model-profile registry's providerOptions(profileKey) for
 *  EVERY debate profile (the deepseek suffix is intentionally absent — it is gated to need-discovery
 *  workers only). The registry test asserts each suffix below actually resolves, so a rename here fails
 *  loudly rather than silently selecting a non-existent option. */
const OPTION_SUFFIX = {
  openaiBalanced: 'openai-balanced',
  openaiQuality: 'openai-quality',
  openaiDeepReasoning: 'openai-deep-reasoning',
  dashscopeThinkingBudget: 'dashscope-thinking-budget',
} as const;

/** A provider_llm execution spec carrying ONE real, profile-key-scoped model_option_id. (execution_mode
 *  'provider_llm' is required by the plan schema whenever a model_option_id is present.) */
function providerSpec(profileKey: string, suffix: string): TopicSelectionAgentExecutionSpec {
  return { execution_mode: 'provider_llm', model_option_id: `${profileKey}.${suffix}` };
}

// ─────────────────────────────────────────────── N6 divergent debate (DISTINCT per-role profile keys) ──

const N6_EXPLORER = TOPIC_SELECTION_V1B_N6_DEBATE_EXPLORER_PROFILE_ID;
const N6_CRITIC = TOPIC_SELECTION_V1B_N6_DEBATE_CRITIC_PROFILE_ID;
const N6_ARBITER = TOPIC_SELECTION_V1B_N6_DEBATE_ARBITER_PROFILE_ID;

export const TOPIC_SELECTION_N6_DEBATE_EXECUTION_PLANS: Record<
  TopicSelectionDebateExecutionPlanName,
  TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1bN6DivergentDebateRoleSlotId>
> = {
  // Empty plan: the resolver returns null for every role -> byte-identical to today's codex/single-profile.
  codex_assisted: { name: 'codex_assisted' },
  provider_compact: {
    name: 'provider_compact',
    roles: {
      n6_debate_explorer: providerSpec(N6_EXPLORER, OPTION_SUFFIX.openaiBalanced),
      n6_debate_critic: providerSpec(N6_CRITIC, OPTION_SUFFIX.openaiBalanced),
      n6_debate_arbiter: providerSpec(N6_ARBITER, OPTION_SUFFIX.openaiBalanced),
    },
  },
  provider_diverse: {
    name: 'provider_diverse',
    roles: {
      // explorer/critic (the divergent workers) take the dashscope thinking-budget alternative; the arbiter
      // (terminal singleton) takes the highest-quality openai option — never an alternative-worker provider.
      n6_debate_explorer: providerSpec(N6_EXPLORER, OPTION_SUFFIX.dashscopeThinkingBudget),
      n6_debate_critic: providerSpec(N6_CRITIC, OPTION_SUFFIX.dashscopeThinkingBudget),
      n6_debate_arbiter: providerSpec(N6_ARBITER, OPTION_SUFFIX.openaiQuality),
    },
  },
};

// ─────────────────────────────────────── N8 bounded debate (SINGLE shared key; diversity via suffix) ──

const N8 = TOPIC_SELECTION_V1B_N8_BOUNDED_DEBATE_PROFILE_ID;

export const TOPIC_SELECTION_N8_DEBATE_EXECUTION_PLANS: Record<
  TopicSelectionDebateExecutionPlanName,
  TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1bN8BoundedDebateRoleSlotId>
> = {
  codex_assisted: { name: 'codex_assisted' },
  provider_compact: {
    name: 'provider_compact',
    roles: {
      n8_debate_assessor_draft: providerSpec(N8, OPTION_SUFFIX.openaiBalanced),
      n8_debate_value_critic: providerSpec(N8, OPTION_SUFFIX.openaiBalanced),
      n8_debate_assessor_repair: providerSpec(N8, OPTION_SUFFIX.openaiBalanced),
      n8_debate_synthesizer_final: providerSpec(N8, OPTION_SUFFIX.openaiBalanced),
    },
  },
  provider_diverse: {
    name: 'provider_diverse',
    roles: {
      n8_debate_assessor_draft: providerSpec(N8, OPTION_SUFFIX.openaiBalanced),
      n8_debate_value_critic: providerSpec(N8, OPTION_SUFFIX.dashscopeThinkingBudget),
      n8_debate_assessor_repair: providerSpec(N8, OPTION_SUFFIX.openaiDeepReasoning),
      // the gate-facing synthesizer (terminal) takes the highest-quality openai option.
      n8_debate_synthesizer_final: providerSpec(N8, OPTION_SUFFIX.openaiQuality),
    },
  },
};

// ──────────────────────────────────── v1c-N2 bounded micro-debate (SINGLE shared key; Option-A caller) ──

const N2 = TOPIC_SELECTION_V1C_BOUNDED_MICRO_DEBATE_PROFILE_ID;

export const TOPIC_SELECTION_V1C_N2_DEBATE_EXECUTION_PLANS: Record<
  TopicSelectionDebateExecutionPlanName,
  TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1cN2BoundedDebateRoleSlotId>
> = {
  codex_assisted: { name: 'codex_assisted' },
  provider_compact: {
    name: 'provider_compact',
    roles: {
      'n2_bounded_micro_debate.promotion_supporter_draft': providerSpec(N2, OPTION_SUFFIX.openaiBalanced),
      'n2_bounded_micro_debate.reviewer_critic_review': providerSpec(N2, OPTION_SUFFIX.openaiBalanced),
      'n2_bounded_micro_debate.promotion_supporter_repair': providerSpec(N2, OPTION_SUFFIX.openaiBalanced),
      'n2_bounded_micro_debate.synthesizer_final': providerSpec(N2, OPTION_SUFFIX.openaiBalanced),
    },
  },
  provider_diverse: {
    name: 'provider_diverse',
    roles: {
      'n2_bounded_micro_debate.promotion_supporter_draft': providerSpec(N2, OPTION_SUFFIX.openaiBalanced),
      'n2_bounded_micro_debate.reviewer_critic_review': providerSpec(N2, OPTION_SUFFIX.dashscopeThinkingBudget),
      'n2_bounded_micro_debate.promotion_supporter_repair': providerSpec(N2, OPTION_SUFFIX.openaiDeepReasoning),
      'n2_bounded_micro_debate.synthesizer_final': providerSpec(N2, OPTION_SUFFIX.openaiQuality),
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────── named-plan selectors ──

/** Select the N6 divergent-debate plan by name (compose with debateLevelToExecutionPlanName(level) to map
 *  an escalation debate_level -> plan; codex_assisted is never produced from a level — it is explicit). */
export function selectN6DebateExecutionPlan(
  name: TopicSelectionDebateExecutionPlanName,
): TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1bN6DivergentDebateRoleSlotId> {
  return TOPIC_SELECTION_N6_DEBATE_EXECUTION_PLANS[name];
}

/** Select the N8 bounded-debate plan by name. */
export function selectN8DebateExecutionPlan(
  name: TopicSelectionDebateExecutionPlanName,
): TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1bN8BoundedDebateRoleSlotId> {
  return TOPIC_SELECTION_N8_DEBATE_EXECUTION_PLANS[name];
}

/** Select the v1c-N2 bounded micro-debate plan by name (the caller resolves it per-slot via
 *  resolveCallerSideDebateModelOptionId — Option A, no v1c-N2 runtime change). */
export function selectV1cN2DebateExecutionPlan(
  name: TopicSelectionDebateExecutionPlanName,
): TopicSelectionNamedDebateExecutionPlan<TopicSelectionV1cN2BoundedDebateRoleSlotId> {
  return TOPIC_SELECTION_V1C_N2_DEBATE_EXECUTION_PLANS[name];
}
