// T-151 Phase 1: the `codex_cli` execution line's runner.
//
// The product drives the Codex CLI itself. Everything the model may see or reach comes from a
// product-owned CODEX_HOME written fresh at every invocation, and everything the product keeps
// comes back as two things: the schema-constrained artifact, and the event trace.
//
// Isolation is why CODEX_HOME is product-owned rather than `--ignore-user-config`: that flag
// suppresses the user's config.toml but NOT their skills, and a probe run read a developer skill
// out of ~/.codex and changed its behaviour because of it (T-151 probe-evidence.md §5).
//
// Session rule (D-4): one fresh thread per invocation attempt. This module has no resume or fork
// path at all, which is what enforces it.

import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

export interface TopicSelectionCodexCliMcpServer {
  /** Server name as the model sees it; also the config.toml table key. */
  name: string;
  command: string;
  args: readonly string[];
  env?: Readonly<Record<string, string>>;
}

export interface TopicSelectionCodexCliUsage {
  input_tokens: number;
  cached_input_tokens: number;
  cache_write_input_tokens: number;
  output_tokens: number;
  reasoning_output_tokens: number;
}

export interface TopicSelectionCodexCliToolCall {
  server: string;
  tool: string;
  status: string;
  error: string | null;
}

export const TOPIC_SELECTION_CODEX_CLI_ERROR_CODES = [
  'CODEX_CLI_TIMEOUT',
  'CODEX_CLI_EXIT_FAILURE',
  'CODEX_CLI_NO_FINAL_MESSAGE',
] as const;
export type TopicSelectionCodexCliErrorCode = (typeof TOPIC_SELECTION_CODEX_CLI_ERROR_CODES)[number];

/** A failed run is a result, not an exception, matching how the orchestrator treats provider
 *  failures — and it still carries its trace, because a failed run's trace is evidence too. */
export type TopicSelectionCodexCliRunOutcome =
  | ({ status: 'succeeded' } & TopicSelectionCodexCliRunResult)
  | {
    status: 'failed';
    error_code: TopicSelectionCodexCliErrorCode;
    message: string;
    runner_version: string;
    thread_id: string | null;
    usage: TopicSelectionCodexCliUsage | null;
    tool_calls: TopicSelectionCodexCliToolCall[];
    trace_events: unknown[];
    stderr_tail: string;
  };

export interface TopicSelectionCodexCliRunResult {
  /** Observed, not declared: read from the binary that actually ran, so it cannot drift. */
  runner_version: string;
  thread_id: string;
  /** Raw text of the final agent message; the caller parses it against its own output contract. */
  final_message: string;
  usage: TopicSelectionCodexCliUsage | null;
  tool_calls: TopicSelectionCodexCliToolCall[];
  /** The full JSONL event stream, verbatim. This is the line's evidence of what happened. */
  trace_events: unknown[];
}

export interface TopicSelectionCodexCliRunInput {
  /** Product-authored prompt packet. Passed on stdin, never as an argv element. */
  prompt: string;
  /** JSON Schema the final response must satisfy; enforced by the CLI, not by us. */
  output_schema: Record<string, unknown>;
  invocation_attempt_id: string;
  mcp_servers?: readonly TopicSelectionCodexCliMcpServer[];
}

export interface TopicSelectionCodexCliSpawnResult {
  stdout: string;
  stderr: string;
  exit_code: number | null;
  timed_out: boolean;
}

export type TopicSelectionCodexCliSpawn = (
  args: readonly string[],
  options: { cwd: string; env: Record<string, string>; stdin: string; timeoutMs: number },
) => Promise<TopicSelectionCodexCliSpawnResult>;

export interface TopicSelectionCodexCliRunnerConfig {
  /** Product-owned CODEX_HOME. Must not be the developer's ~/.codex. */
  codex_home: string;
  model: string;
  reasoning_effort: 'low' | 'medium' | 'high' | 'xhigh' | 'max';
  binary?: string;
  timeout_ms?: number;
}

const DEFAULT_TIMEOUT_MS = 600_000;

/** Approval shape recovered empirically for codex-cli 0.153.4 (probe-evidence.md §7): a granular
 *  policy plus a per-server `approve` mode grants the product's own MCP servers while the sandbox
 *  stays read-only. `auto` does NOT work despite its name. */
export function buildCodexConfigToml(servers: readonly TopicSelectionCodexCliMcpServer[]): string {
  const lines = [
    '# Generated by the product for one codex_cli invocation. Do not edit by hand.',
    'approval_policy = { granular = { sandbox_approval = false, rules = false, mcp_elicitations = false } }',
    'sandbox_mode = "read-only"',
  ];
  for (const server of servers) {
    lines.push('', `[mcp_servers.${server.name}]`);
    lines.push(`command = ${JSON.stringify(server.command)}`);
    lines.push(`args = [${server.args.map((arg) => JSON.stringify(arg)).join(', ')}]`);
    lines.push('default_tools_approval_mode = "approve"');
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push(`[mcp_servers.${server.name}.env]`);
      for (const [key, value] of Object.entries(server.env)) {
        lines.push(`${key} = ${JSON.stringify(value)}`);
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

function parseUsage(value: unknown): TopicSelectionCodexCliUsage | null {
  if (typeof value !== 'object' || value === null) {
    return null;
  }
  const raw = value as Record<string, unknown>;
  const read = (key: string): number => (typeof raw[key] === 'number' ? raw[key] : 0);
  return {
    input_tokens: read('input_tokens'),
    cached_input_tokens: read('cached_input_tokens'),
    cache_write_input_tokens: read('cache_write_input_tokens'),
    output_tokens: read('output_tokens'),
    reasoning_output_tokens: read('reasoning_output_tokens'),
  };
}

/** The CLI streams one JSON object per line. A malformed line is dropped rather than failing the
 *  run: the trace is evidence, and losing one line must not discard a completed artifact. */
export function parseCodexEventStream(stdout: string): {
  events: unknown[];
  threadId: string | null;
  finalMessage: string | null;
  usage: TopicSelectionCodexCliUsage | null;
  toolCalls: TopicSelectionCodexCliToolCall[];
} {
  const events: unknown[] = [];
  let threadId: string | null = null;
  let finalMessage: string | null = null;
  let usage: TopicSelectionCodexCliUsage | null = null;
  const toolCalls: TopicSelectionCodexCliToolCall[] = [];

  for (const line of stdout.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.length === 0) {
      continue;
    }
    let event: unknown;
    try {
      event = JSON.parse(trimmed);
    } catch {
      continue;
    }
    events.push(event);
    if (typeof event !== 'object' || event === null) {
      continue;
    }
    const record = event as Record<string, unknown>;
    const item = typeof record.item === 'object' && record.item !== null
      ? record.item as Record<string, unknown>
      : null;

    if (record.type === 'thread.started' && typeof record.thread_id === 'string') {
      threadId = record.thread_id;
    }
    if (record.type === 'turn.completed') {
      usage = parseUsage(record.usage);
    }
    if (record.type === 'item.completed' && item?.type === 'agent_message' && typeof item.text === 'string') {
      finalMessage = item.text;
    }
    if (record.type === 'item.completed' && item?.type === 'mcp_tool_call') {
      toolCalls.push({
        server: typeof item.server === 'string' ? item.server : '',
        tool: typeof item.tool === 'string' ? item.tool : '',
        status: typeof item.status === 'string' ? item.status : '',
        error: typeof item.error === 'string' ? item.error : null,
      });
    }
  }

  return { events, threadId, finalMessage, usage, toolCalls };
}

const defaultSpawn: TopicSelectionCodexCliSpawn = async (args, options) => new Promise((resolve) => {
  const child = spawn(options.env.CODEX_CLI_BINARY ?? 'codex', [...args], {
    cwd: options.cwd,
    shell: false,
    env: options.env,
  });
  let stdout = '';
  let stderr = '';
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    child.kill('SIGTERM');
  }, options.timeoutMs);
  child.stdout.on('data', (chunk: Buffer) => { stdout += chunk.toString('utf8'); });
  child.stderr.on('data', (chunk: Buffer) => { stderr += chunk.toString('utf8'); });
  child.on('error', (error) => {
    clearTimeout(timer);
    resolve({ stdout, stderr: `${stderr}${error.message}`, exit_code: null, timed_out: timedOut });
  });
  child.on('close', (code) => {
    clearTimeout(timer);
    resolve({ stdout, stderr, exit_code: code, timed_out: timedOut });
  });
  child.stdin.end(options.stdin);
});

export class TopicSelectionCodexCliRunnerService {
  constructor(
    private readonly config: TopicSelectionCodexCliRunnerConfig,
    private readonly spawnCodex: TopicSelectionCodexCliSpawn = defaultSpawn,
  ) {}

  private cachedRunnerVersion: string | null = null;

  /** One invocation attempt, one fresh Codex thread. There is deliberately no resume or fork. */
  async run(input: TopicSelectionCodexCliRunInput): Promise<TopicSelectionCodexCliRunOutcome> {
    const servers = input.mcp_servers ?? [];
    const home = this.config.codex_home;
    await mkdir(home, { recursive: true });
    await writeFile(path.join(home, 'config.toml'), buildCodexConfigToml(servers), 'utf8');

    const schemaPath = path.join(home, `output-schema-${input.invocation_attempt_id}.json`);
    await writeFile(schemaPath, JSON.stringify(input.output_schema), 'utf8');

    const args = [
      'exec',
      '--ephemeral',
      '--skip-git-repo-check',
      '--json',
      '--output-schema', schemaPath,
      '-m', this.config.model,
      '-c', `model_reasoning_effort="${this.config.reasoning_effort}"`,
      '-',
    ];

    const result = await this.spawnCodex(args, {
      cwd: home,
      env: this.buildEnv(),
      stdin: input.prompt,
      timeoutMs: this.config.timeout_ms ?? DEFAULT_TIMEOUT_MS,
    });

    const runnerVersion = await this.runnerVersion();
    const parsed = parseCodexEventStream(result.stdout);
    const failure = (
      errorCode: TopicSelectionCodexCliErrorCode,
      message: string,
    ): TopicSelectionCodexCliRunOutcome => ({
      status: 'failed',
      error_code: errorCode,
      message,
      runner_version: runnerVersion,
      thread_id: parsed.threadId,
      usage: parsed.usage,
      tool_calls: parsed.toolCalls,
      trace_events: parsed.events,
      stderr_tail: result.stderr.slice(-500),
    });

    if (result.timed_out) {
      return failure('CODEX_CLI_TIMEOUT', 'The codex_cli invocation timed out.');
    }
    if (result.exit_code !== 0) {
      return failure('CODEX_CLI_EXIT_FAILURE', `The codex_cli invocation exited with ${String(result.exit_code)}.`);
    }
    if (parsed.threadId === null || parsed.finalMessage === null) {
      return failure('CODEX_CLI_NO_FINAL_MESSAGE', 'The codex_cli invocation produced no final message.');
    }

    return {
      status: 'succeeded',
      runner_version: runnerVersion,
      thread_id: parsed.threadId,
      final_message: parsed.finalMessage,
      usage: parsed.usage,
      tool_calls: parsed.toolCalls,
      trace_events: parsed.events,
    };
  }

  /** The version of the binary that actually ran, resolved once per service instance. Declaring it
   *  in configuration would let it drift from reality, and the provenance claims it is authoritative. */
  private async runnerVersion(): Promise<string> {
    if (this.cachedRunnerVersion === null) {
      const probe = await this.spawnCodex(['--version'], {
        cwd: this.config.codex_home,
        env: this.buildEnv(),
        stdin: '',
        timeoutMs: 30_000,
      });
      this.cachedRunnerVersion = probe.stdout.trim() || 'unknown';
    }
    return this.cachedRunnerVersion;
  }

  /** A deliberately small environment: the runner inherits nothing that could change what the
   *  agent sees. CODEX_HOME points at the product's own directory, so config, skills and any
   *  other CODEX_HOME-relative material are the product's, not the developer's. */
  private buildEnv(): Record<string, string> {
    const env: Record<string, string> = {
      CODEX_HOME: this.config.codex_home,
      PATH: process.env.PATH ?? '/usr/bin:/bin',
    };
    if (this.config.binary) {
      env.CODEX_CLI_BINARY = this.config.binary;
    }
    return env;
  }
}

/** Deployment configuration for the codex_cli line.
 *
 *  These are environment variables rather than `.ai/llm/**` routing config on purpose: CODEX_HOME
 *  has to be provisioned by whoever runs the process, because it is where the Codex credential
 *  lives, and the line is deliberately not a provider route.
 *
 *    TOPIC_SELECTION_CODEX_HOME              product-owned CODEX_HOME; absent disables the line
 *    TOPIC_SELECTION_CODEX_MODEL             model slug, e.g. gpt-6-astra
 *    TOPIC_SELECTION_CODEX_REASONING_EFFORT  low | medium | high | xhigh | max (default high)
 *    TOPIC_SELECTION_CODEX_BINARY            optional path to the codex binary
 *    TOPIC_SELECTION_CODEX_TIMEOUT_MS        optional per-invocation timeout
 *
 *  Returns null when the line is not configured, which leaves it unavailable rather than
 *  half-configured. */
export function createTopicSelectionCodexCliRunnerFromEnv(
  env: NodeJS.ProcessEnv = process.env,
): { runner: TopicSelectionCodexCliRunnerService; model_id: string } | null {
  const codexHome = env.TOPIC_SELECTION_CODEX_HOME?.trim();
  const model = env.TOPIC_SELECTION_CODEX_MODEL?.trim();
  if (!codexHome || !model) {
    return null;
  }
  const effortRaw = env.TOPIC_SELECTION_CODEX_REASONING_EFFORT?.trim() ?? 'high';
  const efforts = ['low', 'medium', 'high', 'xhigh', 'max'] as const;
  const effort = efforts.find((candidate) => candidate === effortRaw);
  if (!effort) {
    throw new Error(`TOPIC_SELECTION_CODEX_REASONING_EFFORT must be one of ${efforts.join(', ')}.`);
  }
  const timeoutRaw = env.TOPIC_SELECTION_CODEX_TIMEOUT_MS?.trim();
  const timeoutMs = timeoutRaw ? Number.parseInt(timeoutRaw, 10) : undefined;
  if (timeoutMs !== undefined && (!Number.isSafeInteger(timeoutMs) || timeoutMs <= 0)) {
    throw new Error('TOPIC_SELECTION_CODEX_TIMEOUT_MS must be a positive integer.');
  }
  return {
    runner: new TopicSelectionCodexCliRunnerService({
      codex_home: codexHome,
      model,
      reasoning_effort: effort,
      binary: env.TOPIC_SELECTION_CODEX_BINARY?.trim() || undefined,
      timeout_ms: timeoutMs,
    }),
    model_id: model,
  };
}
