import { useEffect, useState } from 'react';
import { ReviewerCard, ReviewerCardEmpty } from './ReviewerCard';
import type {
  TopicSelectionResearchSliceOptionRecord,
  TopicSelectionResearchSliceOptionSetRecord,
} from '@paper-engineering-assistant/shared/research-lifecycle/topic-selection-v1b-research-slice-contracts';
import {
  listResearchSliceOptionsByOptionSet,
  selectResearchSliceHuman,
} from '../api/v1b';

type SliceOptionSetCardProps = {
  sliceOptionSets: TopicSelectionResearchSliceOptionSetRecord[];
  /** T-115 — reload v1b stage data after a human slice selection mutates state. */
  onMutated?: () => void;
};

function statusTone(status: string): 'neutral' | 'info' | 'success' | 'warning' | 'danger' {
  if (status === 'selected' || status === 'closed') return 'success';
  if (status === 'pending_human_review') return 'warning';
  return 'info';
}

/**
 * v1b ResearchSliceOptionSet surface — Phase 3.1 read-only view.
 *
 * Lists option sets generated by `PlanResearchSlice` runs, with metadata
 * about which option is recommended/selected and whether human review is
 * required. Write actions are owned by the harness-native v1b path.
 */
export function SliceOptionSetCard({ sliceOptionSets, onMutated }: SliceOptionSetCardProps) {
  const [selectedId, setSelectedId] = useState<string | null>(
    sliceOptionSets[0]?.research_slice_option_set_id ?? null,
  );
  const active = sliceOptionSets.find((item) => item.research_slice_option_set_id === selectedId)
    ?? sliceOptionSets[0]
    ?? null;

  if (!active) {
    return (
      <article data-ui="card">
        <div data-ui="stack" data-direction="col" data-gap="2">
          <p data-ui="text" data-variant="label" data-tone="primary">ResearchSliceOptionSet</p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            该题目卡的 v1b 还没生成 ResearchSliceOptionSet。先确保 v1a 出口 ValidatedNeed + V1bInputBundle 已发布。
          </p>
        </div>
      </article>
    );
  }

  const optionSelector = sliceOptionSets.length > 1 ? (
    <select
      data-ui="select"
      data-size="sm"
      value={active.research_slice_option_set_id}
      onChange={(event) => setSelectedId(event.target.value)}
    >
      {sliceOptionSets.map((item) => (
        <option key={item.research_slice_option_set_id} value={item.research_slice_option_set_id}>
          {item.research_slice_option_set_id} · {item.status}
        </option>
      ))}
    </select>
  ) : null;

  return (
    <ReviewerCard
      kind="ResearchSliceOptionSet"
      subjectId={active.research_slice_option_set_id}
      status={{ label: active.status, tone: statusTone(active.status) }}
      chips={[
        { label: `options ${active.option_count}`, tone: 'info' },
        { label: `high-risk ${active.high_risk_option_count}`, tone: active.high_risk_option_count > 0 ? 'warning' : 'neutral' },
        ...(active.requires_human_review ? [{ label: 'human review', tone: 'warning' as const }] : []),
        ...(sliceOptionSets.length > 1 ? [{ label: `history ${sliceOptionSets.length}`, tone: 'neutral' as const }] : []),
      ]}
      verdict={
        <div data-ui="stack" data-direction="col" data-gap="1">
          <p data-ui="text" data-variant="body" data-tone="primary">
            comparison：{active.comparison_summary || '— 无 comparison_summary —'}
          </p>
          <p data-ui="text" data-variant="caption" data-tone="muted">
            recommended={active.recommended_option_id ?? '—'} · selected={active.selected_option_id ?? '—'}
          </p>
          {optionSelector ? (
            <div data-ui="stack" data-direction="row" data-gap="2" data-align="center">
              <span data-ui="text" data-variant="caption" data-tone="muted">切换 option set</span>
              {optionSelector}
            </div>
          ) : null}
        </div>
      }
      support={
        active.comparison_axes.length === 0 ? (
          <ReviewerCardEmpty label="没有声明的 comparison_axes。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            <p data-ui="text" data-variant="caption" data-tone="primary">
              comparison_axes（{active.comparison_axes.length}）
            </p>
            <ul data-ui="stack" data-direction="col" data-gap="0">
              {active.comparison_axes.slice(0, 6).map((axis, idx) => (
                <li key={`${axis}-${idx}`}>
                  <p data-ui="text" data-variant="caption" data-tone="muted">· {axis}</p>
                </li>
              ))}
            </ul>
          </div>
        )
      }
      challenge={
        active.unresolved_disagreements.length === 0 && active.missing_option_types.length === 0 ? (
          <ReviewerCardEmpty label="无未解 disagreement / missing option type。" />
        ) : (
          <div data-ui="stack" data-direction="col" data-gap="1">
            {active.unresolved_disagreements.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                unresolved_disagreements：{active.unresolved_disagreements.length}
              </p>
            ) : null}
            {active.missing_option_types.length > 0 ? (
              <p data-ui="text" data-variant="caption" data-tone="muted">
                missing_option_types：{active.missing_option_types.join(' · ')}
              </p>
            ) : null}
          </div>
        )
      }
      blockers={
        active.human_review_triggers.length === 0 ? (
          <ReviewerCardEmpty label="无 human_review_triggers。" />
        ) : (
          <div data-ui="stack" data-direction="row" data-gap="1" data-wrap="wrap">
            {active.human_review_triggers.map((trigger) => (
              <span key={trigger} data-ui="badge" data-variant="subtle" data-tone="warning">{trigger}</span>
            ))}
          </div>
        )
      }
      nextActions={
        <div data-ui="stack" data-direction="col" data-gap="2">
          {active.selected_option_id ? (
            <p data-ui="text" data-variant="caption" data-tone="primary">
              → 已选定 option：{active.selected_option_id}
            </p>
          ) : active.status === 'ready_for_selection' ? (
            <SliceSelectionForm optionSet={active} onMutated={onMutated} />
          ) : (
            <ReviewerCardEmpty label={`option set 状态 ${active.status}，暂不可人审选定（可由 harness/agent 路径推进）。`} />
          )}
        </div>
      }
      footer={`created_at=${active.created_at} · updated_at=${active.updated_at}`}
    />
  );
}

type SliceSelectionFormProps = {
  optionSet: TopicSelectionResearchSliceOptionSetRecord;
  onMutated?: () => void;
};

/**
 * T-115 — human N5 slice selection form. Lists the option set's options and
 * POSTs a human selection that the backend runs through the harness in
 * `human_delegated` mode (same ResearchSlice artifact as the codex/native path).
 */
function SliceSelectionForm({ optionSet, onMutated }: SliceSelectionFormProps) {
  const optionSetId = optionSet.research_slice_option_set_id;
  const [options, setOptions] = useState<TopicSelectionResearchSliceOptionRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [selectedOptionId, setSelectedOptionId] = useState('');
  const [rationale, setRationale] = useState('');
  const [reviewerActorId, setReviewerActorId] = useState('reviewer');
  const [confidence, setConfidence] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [blockedStatus, setBlockedStatus] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    setLoadError(null);
    void listResearchSliceOptionsByOptionSet(optionSetId)
      .then((items) => {
        if (!mounted) return;
        setOptions(items);
        setSelectedOptionId(optionSet.recommended_option_id ?? items[0]?.research_slice_option_id ?? '');
      })
      .catch((caught) => {
        if (mounted) setLoadError(caught instanceof Error ? caught.message : '加载 options 失败。');
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, [optionSetId, optionSet.recommended_option_id]);

  const canSubmit = selectedOptionId.trim() !== ''
    && rationale.trim() !== ''
    && reviewerActorId.trim() !== ''
    && !submitting;

  const handleSubmit = async () => {
    setSubmitting(true);
    setSubmitError(null);
    setBlockedStatus(null);
    try {
      const trimmedConfidence = confidence.trim();
      const parsed = trimmedConfidence === '' ? null : Number(trimmedConfidence);
      const result = await selectResearchSliceHuman(optionSetId, {
        selected_option_id: selectedOptionId,
        selection_rationale: rationale.trim(),
        actor: { actor_type: 'human', actor_id: reviewerActorId.trim() },
        confidence: parsed !== null && Number.isFinite(parsed) ? parsed : null,
      });
      if (result.gate_status === 'admitted' || result.gate_status === 'admitted_with_warnings') {
        onMutated?.();
      } else {
        setBlockedStatus(result.gate_status);
      }
    } catch (caught) {
      setSubmitError(caught instanceof Error ? caught.message : '提交 slice 选择失败。');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <section data-ui="section" data-padding="sm">
      <div data-ui="stack" data-direction="col" data-gap="2">
        <p data-ui="text" data-variant="label" data-tone="primary">人审选定 ResearchSlice（N5）</p>
        <p data-ui="text" data-variant="caption" data-tone="muted">
          选定后经 harness 的 human_delegated 路径物化 ResearchSlice（与 agent 路径产出一致）。
        </p>
        {loading ? (
          <p data-ui="text" data-variant="caption" data-tone="muted">加载 options…</p>
        ) : loadError ? (
          <p data-ui="text" data-variant="caption" data-tone="danger">{loadError}</p>
        ) : options.length === 0 ? (
          <ReviewerCardEmpty label="该 option set 暂无 options。" />
        ) : (
          <>
            <div data-ui="stack" data-direction="col" data-gap="1">
              <p data-ui="text" data-variant="caption" data-tone="muted">选项</p>
              <select
                data-ui="select"
                data-size="md"
                value={selectedOptionId}
                onChange={(event) => setSelectedOptionId(event.target.value)}
              >
                {options.map((option) => (
                  <option key={option.research_slice_option_id} value={option.research_slice_option_id}>
                    {option.option_key} · {option.slice_statement.slice(0, 60)}
                  </option>
                ))}
              </select>
            </div>
            <div data-ui="stack" data-direction="col" data-gap="1">
              <p data-ui="text" data-variant="caption" data-tone="muted">Reviewer actor_id（必填）</p>
              <input
                data-ui="input"
                data-size="sm"
                value={reviewerActorId}
                onChange={(event) => setReviewerActorId(event.target.value)}
                placeholder="reviewer-id"
              />
            </div>
            <div data-ui="stack" data-direction="col" data-gap="1">
              <p data-ui="text" data-variant="caption" data-tone="muted">选择理由（必填）</p>
              <textarea
                data-ui="textarea"
                data-size="md"
                rows={3}
                value={rationale}
                onChange={(event) => setRationale(event.target.value)}
                placeholder="为什么选这个 slice：边界 / claim ceiling / 可行性 …"
              />
            </div>
            <div data-ui="stack" data-direction="col" data-gap="1">
              <p data-ui="text" data-variant="caption" data-tone="muted">Confidence（可选，0–1）</p>
              <input
                data-ui="input"
                data-size="sm"
                value={confidence}
                onChange={(event) => setConfidence(event.target.value)}
                placeholder="0.82"
              />
            </div>
            {blockedStatus ? (
              <div data-ui="alert" data-tone="warning">
                <p data-ui="text" data-variant="caption" data-tone="primary">
                  Gate 未放行（{blockedStatus}）。请检查上游证据/约束后重试，或在 trace 查看 blockers。
                </p>
              </div>
            ) : null}
            {submitError ? (
              <p data-ui="text" data-variant="caption" data-tone="danger">{submitError}</p>
            ) : null}
            <div data-ui="stack" data-direction="row" data-gap="1" data-align="center">
              <button
                type="button"
                data-ui="button"
                data-variant="primary"
                data-size="sm"
                disabled={!canSubmit}
                onClick={() => void handleSubmit()}
              >
                {submitting ? '提交中…' : '确认选定'}
              </button>
            </div>
          </>
        )}
      </div>
    </section>
  );
}
